### ISSUE TITLE
Specify file input/output

### ISSUE THREAD

**Issue by unformatt** [Kyborg2011/SoxPlayer#2]
Sorry for the noobish question, I'm not a C guy. How could I change Java_com_sox_player_SoxPlayerActivity_play to accept strings for input file and output file?

**Comment by Kyborg2011** [comment]
Yes, you could. Reading exemples of using sox (in folder jni/sox/src - exemples1.c, 2 ...). Now you can do all thinks, that do SoX. If you need help - write me in e-maol: wkyborgw@gmail.com

**Comment by unformatt** [comment]
I'll check it out, thanks
